import { Club, GameEvent, UserProfile } from './types';

export const SEED_PLAYERS: UserProfile[] = [
  {
    id: 'player-1',
    name: 'Marcus Johnson',
    nickname: 'MJ',
    position: 'SG',
    avatarColor: '#FF6B2C',
    stats: { height: 188, weight: 82, speed: 8, strength: 6, shooting: 9, defense: 7, stamina: 8 },
    bio: 'Catch-and-shoot specialist',
    joinedAt: '2025-01-15T00:00:00.000Z',
  },
  {
    id: 'player-2',
    name: 'Devin Carter',
    nickname: 'D.C.',
    position: 'PG',
    avatarColor: '#3B82F6',
    stats: { height: 183, weight: 78, speed: 9, strength: 5, shooting: 7, defense: 6, stamina: 9 },
    bio: 'Floor general with court vision',
    joinedAt: '2025-02-01T00:00:00.000Z',
  },
  {
    id: 'player-3',
    name: 'Tyler Brooks',
    position: 'PF',
    avatarColor: '#22C55E',
    stats: { height: 198, weight: 95, speed: 6, strength: 9, shooting: 5, defense: 8, stamina: 7 },
    bio: 'Paint beast and rebound machine',
    joinedAt: '2025-02-10T00:00:00.000Z',
  },
  {
    id: 'player-4',
    name: 'Jordan Lee',
    nickname: 'J-Lee',
    position: 'SF',
    avatarColor: '#A855F7',
    stats: { height: 193, weight: 86, speed: 7, strength: 7, shooting: 7, defense: 8, stamina: 7 },
    bio: 'Two-way wing player',
    joinedAt: '2025-03-05T00:00:00.000Z',
  },
  {
    id: 'player-5',
    name: 'Chris Nguyen',
    position: 'C',
    avatarColor: '#FFD166',
    stats: { height: 206, weight: 102, speed: 5, strength: 10, shooting: 4, defense: 9, stamina: 6 },
    bio: 'Rim protector and anchor',
    joinedAt: '2025-03-12T00:00:00.000Z',
  },
  {
    id: 'player-6',
    name: 'Alex Rivera',
    position: 'SG',
    avatarColor: '#EC4899',
    stats: { height: 185, weight: 80, speed: 8, strength: 6, shooting: 8, defense: 6, stamina: 8 },
    joinedAt: '2025-04-01T00:00:00.000Z',
  },
  {
    id: 'player-7',
    name: 'Sam Wilson',
    position: 'PF',
    avatarColor: '#14B8A6',
    stats: { height: 196, weight: 92, speed: 6, strength: 8, shooting: 6, defense: 7, stamina: 7 },
    joinedAt: '2025-04-15T00:00:00.000Z',
  },
  {
    id: 'player-8',
    name: 'Mike Torres',
    position: 'PG',
    avatarColor: '#F97316',
    stats: { height: 178, weight: 74, speed: 9, strength: 4, shooting: 6, defense: 5, stamina: 9 },
    joinedAt: '2025-05-01T00:00:00.000Z',
  },
];

export const SEED_CLUBS: Club[] = [
  {
    id: 'club-1',
    name: 'Downtown Hoopers',
    description: 'Weekly pickup runs every Tuesday and Thursday at the community center.',
    location: 'Central Park Courts',
    memberIds: ['player-1', 'player-2', 'player-3', 'player-4', 'player-5'],
    adminId: 'player-1',
    iconColor: '#FF6B2C',
    createdAt: '2025-01-20T00:00:00.000Z',
  },
  {
    id: 'club-2',
    name: 'Sunset Ballers',
    description: 'Competitive 5v5 games with stat tracking and post-game highlights.',
    location: 'Sunset Recreation Center',
    memberIds: ['player-2', 'player-4', 'player-6', 'player-7', 'player-8'],
    adminId: 'player-2',
    iconColor: '#3B82F6',
    createdAt: '2025-02-15T00:00:00.000Z',
  },
  {
    id: 'club-3',
    name: 'Weekend Warriors',
    description: 'Casual Saturday morning runs. All skill levels welcome!',
    location: 'Riverside Gymnasium',
    memberIds: ['player-1', 'player-3', 'player-6', 'player-8'],
    adminId: 'player-3',
    iconColor: '#22C55E',
    createdAt: '2025-03-01T00:00:00.000Z',
  },
];

export const SEED_EVENTS: GameEvent[] = [
  {
    id: 'event-1',
    clubId: 'club-1',
    title: 'Tuesday Night Run',
    description: 'Full court 5v5. Bring your A-game!',
    location: 'Central Park Courts - Court 2',
    dateTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    maxPlayers: 10,
    participantIds: ['player-1', 'player-2', 'player-3', 'player-4', 'player-5', 'player-6'],
    shuffled: false,
    createdBy: 'player-1',
  },
  {
    id: 'event-2',
    clubId: 'club-2',
    title: 'Sunset Showdown',
    description: 'Competitive scrimmage with balanced teams.',
    location: 'Sunset Recreation Center',
    dateTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    maxPlayers: 10,
    participantIds: ['player-2', 'player-4', 'player-6', 'player-7', 'player-8'],
    shuffled: false,
    createdBy: 'player-2',
  },
  {
    id: 'event-3',
    clubId: 'club-3',
    title: 'Saturday Morning Pickup',
    description: 'Relaxed run to start the weekend right.',
    location: 'Riverside Gymnasium',
    dateTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    maxPlayers: 12,
    participantIds: ['player-1', 'player-3', 'player-6', 'player-8'],
    shuffled: false,
    createdBy: 'player-3',
  },
];

export const AVATAR_COLORS = [
  '#FF6B2C',
  '#3B82F6',
  '#22C55E',
  '#A855F7',
  '#FFD166',
  '#EC4899',
  '#14B8A6',
  '#F97316',
];
